import { PERMISSIONS } from "../constants/permissions.js";
import { ROLE_CODES } from "../constants/roles.js";

export const permissionCatalog = [
  { code: PERMISSIONS.ORGANIZATION_CREATE, resource: "organization", action: "create", description: "Create organizations" },
  { code: PERMISSIONS.ORGANIZATION_READ, resource: "organization", action: "read", description: "View organizations" },
  { code: PERMISSIONS.ORGANIZATION_UPDATE, resource: "organization", action: "update", description: "Update organizations" },
  { code: PERMISSIONS.ORGANIZATION_DELETE, resource: "organization", action: "delete", description: "Delete organizations" },
  { code: PERMISSIONS.ORGANIZATION_SUSPEND, resource: "organization", action: "suspend", description: "Suspend organizations" },
  { code: PERMISSIONS.ORGANIZATION_ACTIVATE, resource: "organization", action: "activate", description: "Activate organizations" },
  { code: PERMISSIONS.ORGANIZATION_ANALYTICS, resource: "organization", action: "analytics", description: "View global analytics" },
  { code: PERMISSIONS.USER_CREATE, resource: "user", action: "create", description: "Create users" },
  { code: PERMISSIONS.USER_READ, resource: "user", action: "read", description: "View users" },
  { code: PERMISSIONS.USER_UPDATE, resource: "user", action: "update", description: "Update users" },
  { code: PERMISSIONS.USER_DELETE, resource: "user", action: "delete", description: "Delete users" },
  { code: PERMISSIONS.USER_INVITE, resource: "user", action: "invite", description: "Invite users" },
  { code: PERMISSIONS.USER_ASSIGN_ROLE, resource: "user", action: "assign_role", description: "Assign roles" },
  { code: PERMISSIONS.USER_DEACTIVATE, resource: "user", action: "deactivate", description: "Deactivate users" },
  { code: PERMISSIONS.USER_RESET_PASSWORD, resource: "user", action: "reset_password", description: "Reset user passwords" },
  { code: PERMISSIONS.DRIVER_CREATE, resource: "driver", action: "create", description: "Create drivers" },
  { code: PERMISSIONS.DRIVER_READ, resource: "driver", action: "read", description: "View drivers" },
  { code: PERMISSIONS.DRIVER_UPDATE, resource: "driver", action: "update", description: "Update drivers" },
  { code: PERMISSIONS.DRIVER_ASSIGN, resource: "driver", action: "assign", description: "Assign drivers to trips" },
  { code: PERMISSIONS.DRIVER_STATUS, resource: "driver", action: "status", description: "Update driver status" },
  { code: PERMISSIONS.DRIVER_SAFETY, resource: "driver", action: "safety", description: "Manage driver safety" },
  { code: PERMISSIONS.DRIVER_DOCUMENT_UPLOAD, resource: "driver_document", action: "upload", description: "Upload driver documents" },
  { code: PERMISSIONS.VEHICLE_CREATE, resource: "vehicle", action: "create", description: "Create vehicles" },
  { code: PERMISSIONS.VEHICLE_READ, resource: "vehicle", action: "read", description: "View vehicles" },
  { code: PERMISSIONS.VEHICLE_UPDATE, resource: "vehicle", action: "update", description: "Update vehicles" },
  { code: PERMISSIONS.VEHICLE_DELETE, resource: "vehicle", action: "delete", description: "Delete vehicles" },
  { code: PERMISSIONS.TRIP_CREATE, resource: "trip", action: "create", description: "Create trips" },
  { code: PERMISSIONS.TRIP_READ, resource: "trip", action: "read", description: "View trips" },
  { code: PERMISSIONS.TRIP_DISPATCH, resource: "trip", action: "dispatch", description: "Dispatch trips" },
  { code: PERMISSIONS.TRIP_COMPLETE, resource: "trip", action: "complete", description: "Complete trips" },
  { code: PERMISSIONS.TRIP_CANCEL, resource: "trip", action: "cancel", description: "Cancel trips" },
  { code: PERMISSIONS.MAINTENANCE_CREATE, resource: "maintenance", action: "create", description: "Create maintenance logs" },
  { code: PERMISSIONS.MAINTENANCE_READ, resource: "maintenance", action: "read", description: "View maintenance logs" },
  { code: PERMISSIONS.MAINTENANCE_UPDATE, resource: "maintenance", action: "update", description: "Update maintenance logs" },
  { code: PERMISSIONS.MAINTENANCE_CLOSE, resource: "maintenance", action: "close", description: "Close maintenance logs" },
  { code: PERMISSIONS.FUEL_CREATE, resource: "fuel", action: "create", description: "Create fuel logs" },
  { code: PERMISSIONS.FUEL_READ, resource: "fuel", action: "read", description: "View fuel logs" },
  { code: PERMISSIONS.FUEL_UPDATE, resource: "fuel", action: "update", description: "Update fuel logs" },
  { code: PERMISSIONS.FUEL_DELETE, resource: "fuel", action: "delete", description: "Delete fuel logs" },
  { code: PERMISSIONS.EXPENSE_CREATE, resource: "expense", action: "create", description: "Create expenses" },
  { code: PERMISSIONS.EXPENSE_READ, resource: "expense", action: "read", description: "View expenses" },
  { code: PERMISSIONS.EXPENSE_UPDATE, resource: "expense", action: "update", description: "Update expenses" },
  { code: PERMISSIONS.EXPENSE_DELETE, resource: "expense", action: "delete", description: "Delete expenses" },
  { code: PERMISSIONS.DASHBOARD_READ, resource: "dashboard", action: "read", description: "View dashboards" },
  { code: PERMISSIONS.REPORT_READ, resource: "report", action: "read", description: "View reports" },
  { code: PERMISSIONS.REPORT_EXPORT, resource: "report", action: "export", description: "Export reports" },
  { code: PERMISSIONS.AUDIT_READ, resource: "audit", action: "read", description: "View audit logs" },
  { code: PERMISSIONS.NOTIFICATION_READ, resource: "notification", action: "read", description: "View notifications" },
];

export const rolePermissionMap: Record<string, string[]> = {
  [ROLE_CODES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLE_CODES.FLEET_MANAGER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.USER_DEACTIVATE,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.DRIVER_READ,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.MAINTENANCE_CLOSE,
    PERMISSIONS.FUEL_CREATE,
    PERMISSIONS.FUEL_READ,
    PERMISSIONS.FUEL_UPDATE,
    PERMISSIONS.FUEL_DELETE,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  [ROLE_CODES.DISPATCHER]: [
    PERMISSIONS.DRIVER_CREATE,
    PERMISSIONS.DRIVER_READ,
    PERMISSIONS.DRIVER_UPDATE,
    PERMISSIONS.DRIVER_ASSIGN,
    PERMISSIONS.DRIVER_STATUS,
    PERMISSIONS.DRIVER_DOCUMENT_UPLOAD,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRIP_CREATE,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.TRIP_DISPATCH,
    PERMISSIONS.TRIP_COMPLETE,
    PERMISSIONS.TRIP_CANCEL,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  [ROLE_CODES.SAFETY_OFFICER]: [
    PERMISSIONS.DRIVER_READ,
    PERMISSIONS.DRIVER_SAFETY,
    PERMISSIONS.DRIVER_STATUS,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  [ROLE_CODES.FINANCIAL_ANALYST]: [
    PERMISSIONS.FUEL_READ,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.NOTIFICATION_READ,
  ],
};

