export const PERMISSIONS = {
  ORGANIZATION_CREATE: "organization:create",
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",
  ORGANIZATION_DELETE: "organization:delete",
  ORGANIZATION_SUSPEND: "organization:suspend",
  ORGANIZATION_ACTIVATE: "organization:activate",
  ORGANIZATION_ANALYTICS: "organization:analytics",
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_INVITE: "user:invite",
  USER_ASSIGN_ROLE: "user:assign_role",
  USER_DEACTIVATE: "user:deactivate",
  USER_RESET_PASSWORD: "user:reset_password",
  DRIVER_CREATE: "driver:create",
  DRIVER_READ: "driver:read",
  DRIVER_UPDATE: "driver:update",
  DRIVER_ASSIGN: "driver:assign",
  DRIVER_STATUS: "driver:status",
  DRIVER_SAFETY: "driver:safety",
  DRIVER_DOCUMENT_UPLOAD: "driver_document:upload",
  VEHICLE_CREATE: "vehicle:create",
  VEHICLE_READ: "vehicle:read",
  VEHICLE_UPDATE: "vehicle:update",
  VEHICLE_DELETE: "vehicle:delete",
  TRIP_CREATE: "trip:create",
  TRIP_READ: "trip:read",
  TRIP_DISPATCH: "trip:dispatch",
  TRIP_COMPLETE: "trip:complete",
  TRIP_CANCEL: "trip:cancel",
  MAINTENANCE_CREATE: "maintenance:create",
  MAINTENANCE_READ: "maintenance:read",
  MAINTENANCE_UPDATE: "maintenance:update",
  MAINTENANCE_CLOSE: "maintenance:close",
  FUEL_CREATE: "fuel:create",
  FUEL_READ: "fuel:read",
  FUEL_UPDATE: "fuel:update",
  FUEL_DELETE: "fuel:delete",
  EXPENSE_CREATE: "expense:create",
  EXPENSE_READ: "expense:read",
  EXPENSE_UPDATE: "expense:update",
  EXPENSE_DELETE: "expense:delete",
  DASHBOARD_READ: "dashboard:read",
  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",
  AUDIT_READ: "audit:read",
  NOTIFICATION_READ: "notification:read",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

